### PR TITLE
chore: Update for Django 5 compatibility

### PR DESCRIPTION
**Pull request by Rhevin**
Hello 👋🏻 I tried to refactor and lint code and make it compatible with Django 5
Since Django 3 is deprecated and python3.8 almost outdated

https://endoflife.date/django

Next, we can add dependabot to make auto-update dependencies.

### CODE REVIEW

**Comment by allo-** [comment]
Hello! First: Thanks for the effort. I have a few questions before merging:

- It looks like you used a source formatter. Can you give a short summary of the changes not related to automatic formatting? Are there any issues I need to be aware of when upgrading to a new Django major version?
- If there are major changes, did you test all usual workflows or do I need to check things you couldn't check?
- I never used the docker file myself. I also currently do not have a setup to test it, it would be especially good to know if it is working. On the other hand, I guess when it works on Debian python it should probably also work on recent alpine.

**Comment by Rhevin** [comment]
Thanks for your reply

- I am using this to format code https://github.com/astral-sh/ruff or this https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff in VSCode
It helps to make code standard and have the same style or format, remove unintentional extra spaces, and sort import to make code more accessible and consistent to read.

- changes that are not related to the format, mainly on the url.py file `url` was replaced by `path`
and `from django.utils.translation import gettext as _` replaced `from django.utils.translation import ugettext as _` on forms.py

- I didn't see any issue from my end. I am testing this using the docker and Debian 12.4 using Python 3.11.2 and Mac silicon, the same Python version. The only problem I have is that I couldn't download the extension. I believe it happened because I didn't create this folder
I have deployed on this https://ffprofile.rhev.in/#start using docker. You also can inspect this 😄 

- later, we can create automated docker images release using github action, which will make it easy to pull or download generated images directly from github

**Comment by allo-** [comment]
I look tomorrow or at the weekend into it. Looks good to me so far.
I started to use black for formatting lately. Maybe I should reformat the rest of the code as well.

**Comment by Rhevin** [comment]
Nice, I prefer Ruff because it's faster and has isort function, so we can sort import and make it more organized.

Also, it's nice to enable these options on VSCode to remove extra whitespace 😄 
image

I see a lot of extra whitespace on the settings file 😄 

I also like to add this option to my config 
image

**Pull request merged**
